# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  install:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x install
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'
    - run: npm install
    
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.x test
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: 'npm'
    - run: npm run test
